portfolio:
    resource: "@PortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /app

home_redirect:
    path: /portfolio
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: portfolio_default_index
        permanent: true